### ISSUE TITLE
При ответе корректно отвечает про модель, но называет ее неправильно (как в заданном вопросе) 

### ISSUE THREAD

**Issue by GalinaErshova** [terrainternship/KIA-GPT#10]
![image](https://github.com/terrainternship/KIA-GPT/assets/136462131/18e81e51-99d1-43fa-9e01-70d1b3712d45) . 

Пока не ясно правильно это или нет. Наверное, ожидаемо, что в ответе комплектация должна называться корректно, а не повторять опечатку пользователя.

**Comment by innovator1984** [comment]
Исправлено через промпт. Не воспроизводится.

**Comment by GalinaErshova** [comment]
В рамках этапа 2 тестирования не повторялось.
