### ISSUE TITLE
отсутствует ссылка в ответе

### ISSUE THREAD

**Issue by VVadim91** [terrainternship/KIA-GPT#13]
при выводе ответа про Kia Picanto "Более подробную информацию о дизайне Kia Picanto вы можете найти на нашем официальном сайте: [ссылка на
 сайт]"

Вы можете ознакомиться с подробной информацией о
 комплектации "Classic" для Kia Picanto на официальном сайте KIA по ссылке: [ссылка на сайт с информацией о комплектации "Classic" для Kia Picanto]

Дополнительную информацию о возможностях Kia Rio вы можете найти на официальном сайте KIA: [ссылка на сайт KIA]

Более подробную информацию о литых дисках Kia Rio вы можете найти на
 официальном сайте KIA по ссылке: [ссылка на официальный сайт KIA с информацией о литых дисках Kia Rio]

**Comment by GalinaErshova** [comment]
В новой серии ошибки подобного рода остались
