### ISSUE TITLE
Некорретные ссылки на модели

### ISSUE THREAD

**Issue by GalinaErshova** [terrainternship/KIA-GPT#15]
Похоже, чтр в БЗ старые ссылки на модели 

https://www.kia.ru/models/cerato/

При проверке доступна https://www.kia.ru/models/cerato/desc/

**Comment by GalinaErshova** [comment]
Похоже, что обрезает ссылки. В БЗ корректная ссылка 
![image](https://github.com/terrainternship/KIA-GPT/assets/136462131/52de82a5-daa1-4090-ad0d-340c51938eae)

**Comment by GalinaErshova** [comment]
![image](https://github.com/terrainternship/KIA-GPT/assets/136462131/f4f727bc-aa17-4f02-b510-0a59b8002d28)
![image](https://github.com/terrainternship/KIA-GPT/assets/136462131/98711542-608c-4c98-8a8b-10791a2ce9f0)

**Comment by TasksAndreySorokin** [comment]
Исправлено?

**Comment by GalinaErshova** [comment]
Fixed
