### ISSUE TITLE
Путаница в моделях и комплектациях

### ISSUE THREAD

**Issue by GalinaErshova** [terrainternship/KIA-GPT#19]
В вопросе явно не указана модель, но есть длинный рассказ. При этом модель явно не упоминается. 

**Какие комплектации присутствуют в GT Line?** | В комплектацию GT Line входят следующие опции: 1. Спортивный передний бампер 2. Легкосплавные диски 17" с шинами 225/45 R17 3. Спортивное рулевое колесо с эмблемой "GT Line" 4. Система предупреждения о столкновении с автомобилем в слепой зоне (BCW) 5. Система предупреждения бокового столкновения при выезде с парковки задним ходом (RCCW) 6. Светодиодные дневные ходовые огни 7. Светодиодные фары 8. Светодиодные задние фонари 9. Cветодиодные повторители указателя поворота на боковых зеркалах заднего вида 10. Подрулевые "лепестки" переключения передач 11. Двухзонный климат-контроль 12. Задние датчики парковки 13. Датчик дождя 14. Задержка выключения фар при закрывании замков 15. Система бесключевого доступа Smart Key и запуск двигателя кнопкой 16. Камера заднего вида 17. Навигационная система 10,25'' с поддержкой Apple Carplay и Android Auto 18. Премиальная аудиосистема JBL с 6 динамиками, сабвуфером и внешним усилителем 19. Приборная панель Supervision c цветным дисплеем 4.2'' 20. Задняя независимая подвеска 21. Задний центральный подлокотник с подстаканниками 22. Салонное зеркало заднего вида с автоматическим затемнением 23. Электрорегулировка поясничного подпора сиденья водителя и переднего пассажира Это лишь некоторые из опций, которые входят в комплектацию GT Line. Если вас интересуют более подробные сведения или вы хотите узнать о других комплектациях, я могу предоставить дополнительную информацию.

**Comment by musicnova** [comment]
База Парсера не содержит об этом информации, пусть Алгоритмы промптом запретят о таком спрашивать, если не сказали какая Модель авто конкретно.

**Comment by musicnova** [comment]
иначе бред, надо писать ответ на 5 страниц про каждую марку или выводить табличку из PDF файла.

**Comment by GalinaErshova** [comment]
В рамках этапа 2 тестирования ошибок такого класса стало меньше. 
Пока закрою, что бы работать точечно.
