### ISSUE TITLE
Галлюцинации ссылок при выходе вопроса за БЗ

### ISSUE THREAD

**Issue by innovator1984** [terrainternship/KIA-GPT#22]
Вот пример

Yo Basov:
Здравствуйте, я еду к вам чинить машину. Подскажите, сколько сейчас стоят тормозные колодки на вашем сайте?

kiaGPT_test:
Здравствуйте! Чтобы узнать актуальную цену на тормозные колодки на нашем сайте, вам необходимо перейти по ссылке: [ссылка на сайт с тормозными колодками]. Там вы сможете
 найти информацию о наличии и стоимости тормозных колодок для вашей модели автомобиля. Если у вас возникнут дополнительные вопросы или нужна помощь, не стесняйтесь
 обращаться.

**Comment by innovator1984** [comment]
Вот шикарный пример. Тут опять же проще обработку делать и галлюцинирующую ссылку заменять на kia ru. Хотя можно и через Google api найти первую страницу по запросу site:kia.ru ссылка на сайт с тормозными колодками и подставить в ответе.

**Comment by GalinaErshova** [comment]
Про подобые ссылки есть отдельное issue
