### ISSUE TITLE
Переделать алгоритм! под чанк с <>

### ISSUE THREAD

**Issue by TasksAndreySorokin** [terrainternship/KIA-GPT#25]

**Comment by innovator1984** [comment]
Overlap 2 непонятно как Объединить с этими <> так, чтобы заголовок первым шёл. Ручной overlap 2 изобретать придется.

**Comment by innovator1984** [comment]
Тут какие то есть подсказки
https://towardsdatascience.com/how-i-turned-my-companys-docs-into-a-searchable-database-with-openai-4f2d34bd8736

**Comment by GalinaErshova** [comment]
Мне кажется пока не надо, так как с # вроде хорошо собирается. 
Внутри ничено не бьется только по тем разделам, что выделены знаками (то есть большой и длинный текст не разбивается на доп чанки)  и мы можем контролировать содержимое всех чанков.

**Comment by innovator1984** [comment]
Закрывайте тогда задачу.
