### ISSUE TITLE
Не обрабатываются ссылки на фото и видео пользователя

### ISSUE THREAD

**Issue by innovator1984** [terrainternship/KIA-GPT#26]
Вот пример:
Yo Basov:
Здравствуйте, только купил машину у вас вчера. Сфотографировал после салона. Так и должно было быть? https://motorsmarine.ru/800/600/https/i.ytimg.com/vi/_hDgiJgyfe0/mqdefault.jpg

kiaGPT_test:
Здравствуйте! Спасибо за обращение. К сожалению, я не могу просмотреть фотографию, которую вы предоставили. Однако, если у вас есть вопросы или проблемы с вашей новой
 машиной, я готов помочь. Пожалуйста, уточните, что вас интересует или какую информацию вы ищете.

Пожалуйста, оцените качество ответа от -2 до 2:

Спасибо за оценку 1

Yo Basov:
Изображение приложено. 

Yo Basov:
Что это я вас спрашиваю?

kiaGPT_test:
Извините, но я не могу ответить на ваш вопрос, так как вы не задали конкретного вопроса о продуктах или услугах компании KIA. Если у вас есть какие-либо вопросы о
 моделях автомобилей, запчастях, специальных предложениях, сервисе, технологиях или программном обеспечении, пожалуйста, уточните свой вопрос, и я с удовольствием помогу
 вам.

Пожалуйста, оцените качество ответа от -2 до 2:

Спасибо за оценку 0

**Comment by innovator1984** [comment]
Совместно решили, что это не баг, а фича. Можно так оставить.

**Comment by GalinaErshova** [comment]
Out of scope
