### ISSUE TITLE
Бот не распознает аудио сообщения пользователя и ссылки на аудио сообщения

### ISSUE THREAD

**Issue by musicnova** [terrainternship/KIA-GPT#27]
Привет, купил машину. Как мне послушать в салоне аудиокнигу https://biab.ru/audio/Dubrovskiy01.mp3

**Comment by musicnova** [comment]
kiaGPT_test, [19.09.2023 16:43]
Здравствуйте! Для прослушивания аудиокниги в салоне вашего автомобиля KIA, вам потребуется подключить ваше мобильное устройство к аудиосистеме автомобиля. Это можно сделать через Bluetooth или USB-порт, в зависимости от модели вашего автомобиля и доступных опций. После подключения вашего устройства, вы можете открыть ссылку на аудиокнигу в браузере или приложении на вашем мобильном устройстве и начать воспроизведение. Звук будет передаваться через аудиосистему автомобиля. Автомобили KIA оснащены аудиосистемами премиум класса от производителей JBL, harman/kardon, Bose, Krell, Lexicon. Эти системы обеспечивают высокую четкость звучания, благодаря технологии Clari-Fi, которая повышает качество проигрывания MP3. Если у вас возникнут проблемы с подключением или воспроизведением аудиокниги, пожалуйста, сообщите мне, и я помогу вам решить их.

kiaGPT_test, [19.09.2023 16:43]
Пожалуйста, оцените качество ответа от -2 до 2:

kiaGPT_test, [19.09.2023 16:46]
Спасибо за оценку 1

**Comment by GalinaErshova** [comment]
Out of scope
