### ISSUE TITLE
Бот не синтезирует речь в ответ на аудио сообщения пользователя

### ISSUE THREAD

**Issue by musicnova** [terrainternship/KIA-GPT#28]
Привет, прочитай мне аудиокнигу https://biab.ru/audio/Dubrovskiy01.mp3

**Comment by musicnova** [comment]
kiaGPT_test, [19.09.2023 16:47]
Извините, но моя основная задача - предоставлять информацию о продуктах и услугах KIA. Я не могу прочитать вам аудиокнигу. Однако, если у вас есть вопросы о том, как воспроизвести аудиокнигу в вашем автомобиле KIA, я с удовольствием помогу вам с этим.

kiaGPT_test, [19.09.2023 16:47]
Пожалуйста, оцените качество ответа от -2 до 2:

kiaGPT_test, [19.09.2023 16:48]
Спасибо за оценку 2

**Comment by GalinaErshova** [comment]
Out of scope.
